### ISSUE TITLE
Just One Question!

### ISSUE THREAD

**Issue by NexifyUS** [Ethical-H4CK3R/Pulse#11]
So I Tried Running This on My Windows Machine and It Said This In Python Shell When I Went To Run It

**_Traceback (most recent call last):
  File "C:\Users\Nick\Desktop\Pulse-master\pulse.py", line 13, in <module>
    from Core.tor import TorManager
  File "C:\Users\Nick\Desktop\Pulse-master\Core\tor.py", line 3, in <module>
    import socks
ImportError: No module named socks_** 

I Have Tor Browser Installed Also

**Comment by Ethical-H4CK3R** [comment]
Is not built for windows, but try: pip install pysocks

**Comment by NexifyUS** [comment]
@Ethical-H4CK3R it didnt work :( well sorry to waste your time
