### ISSUE TITLE
TorManager

### ISSUE THREAD

**Issue by mhmejren** [Ethical-H4CK3R/Pulse#12]
hello, 

I'm facing an issue, using Kali Linux

Traceback (most recent call last):
  File "pulse.py", line 13, in <module>
    from Core.tor import TorManager
  File "/root/Desktop/Pulse-master/Core/tor.py", line 3, in <module>
    import socks
ImportError: No module named socks

**Comment by 1337r00t** [comment]
1 - Install https://pypi.python.org/packages/7d/38/edca891ce16827a1de45cc347e4b6c22311eba25838b9825a5e6c48cf560/PySocks-1.6.7.tar.gz#md5=07007ec7ed46292dab06013f2e3af365
2- UnZip for PySocks-1.6.7.tar.g
3- Run Terminal
4 - write : setup.py install
