### ISSUE TITLE
New Issue

### ISSUE THREAD

**Issue by rE-b00t** [Ethical-H4CK3R/Pulse#14]
Last week I was able to use this, but today I cant, I am using the same thing, but for some reason, I can't anymore I used your Instagram.git, I got the same issue, [-] installing tor... and then [-] please install tor for no reason it always worked, I saw some other person experiencing the same issue and he never got it fixed so can you please help me?

**Comment by takhar1995** [comment]
[-] Web-Site: Facebook
  [-] Proxy Ip: 
  [-] Wordlist: paas.txt
  [-] Username: Takharvikram22@Gmail.Com
  [-] Password: 
  [-] Attempts: 
  [-] Account Locked: False

  +-------------------+

  [-] Obtaining Proxy IP ...













  [-] Web-Site: Facebook
  [-] Proxy Ip: 216.239.90.19
  [-] Wordlist: paas.txt
  [-] Username: Takharvikram22@Gmail.Com
  [-] Password: 
  [-] Attempts: 
  [-] Account Locked: False

  +-------------------+

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "pulse.py", line 120, in setupPasswords
    with open(self.wordlist,'r') as passwords:
IOError: [Errno 2] No such file or directory: 'paas.txt'
