### ISSUE TITLE
solve please 

### ISSUE THREAD

**Issue by takhar1995** [Ethical-H4CK3R/Pulse#18]
[-] Web-Site: Facebook
  [-] Proxy Ip: 
  [-] Wordlist: paas.txt
  [-] Username: Takharvikram22@Gmail.Com
  [-] Password: 
  [-] Attempts: 
  [-] Account Locked: False

  +-------------------+

  [-] Obtaining Proxy IP ...

  [-] Web-Site: Facebook
  [-] Proxy Ip: 216.239.90.19
  [-] Wordlist: paas.txt
  [-] Username: Takharvikram22@Gmail.Com
  [-] Password: 
  [-] Attempts: 
  [-] Account Locked: False

  +-------------------+

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "pulse.py", line 120, in setupPasswords
    with open(self.wordlist,'r') as passwords:
IOError: [Errno 2] No such file or directory: 'paas.txt'

**Comment by poopg05454** [comment]
I
