### ISSUE TITLE
Tor Browser

### ISSUE THREAD

**Issue by mrmaldita** [Ethical-H4CK3R/Pulse#20]
Please help me. When I try to run the script it says "Installing Tor browser" then new line it says "Please Install tor". Even tho I have installed tor already but still wondering how come Tor browser?

**Comment by Ethical-H4CK3R** [comment]
```sh
echo "deb http://http.kali.org/kali kali-rolling main contrib non-free" > /etc/apt/sources.list && apt-get update && apt-get install tor -y && apt autoremove -y
```
