### ISSUE TITLE
Hi. Hello. Good Brother. Beloved Brother. If there any way to use Pulse or HyprPulse, or Faitagram Script, On Windows 10.

### ISSUE THREAD

**Issue by glerinsonum** [Ethical-H4CK3R/Pulse#28]
Hi. Hello. Good Brother. Beloved Brother. If there any way to use Pulse or HyprPulse, or Faitagram Script, On Windows 10. @Ethical-H4CK3R

**Comment by Bitwise-01** [comment]
Windows is not really good for hacking, it makes everything much more
difficult than it really is.

**Comment by glerinsonum** [comment]
@Ethical-H4CK3R Ok

**Comment by d3ibis** [comment]
u can check reqs & u must have python on windows BUT as @Pure-L0G1C mentioned that windows is not good for doing this, preferred Kali (:

**Comment by Bitwise-01** [comment]
No, there’s not.
