### ISSUE TITLE
how to make it work on Ubuntu 16.4

### ISSUE THREAD

**Issue by Mehran** [Ethical-H4CK3R/Pulse#3]
i Just Comment these two lines
```
if not 'kali' in platform():
  exit('Kali Linux 2.0 required')
```

script run but seems not work and not Access Granted !

**Comment by Ethical-H4CK3R** [comment]
it's only for kali linux

**Comment by Mehran** [comment]
Yes but why ? i also try kali Docker but cause it need 127.0.0.1 for TOR i got some errors .
