### ISSUE TITLE
Twitter false Alarm

### ISSUE THREAD

**Issue by Mehran** [Ethical-H4CK3R/Pulse#5]
for Twitter it said Access Granted but Password is wrong .

**Comment by Ethical-H4CK3R** [comment]
thanks for letting me know

**Comment by mehranexpert** [comment]
for twitter sometimes it wait many and pause to continue . can you add some timeout for proxy ?

**Comment by Ethical-H4CK3R** [comment]
when Twitter locks the account, the program will pause and wait for the account to unlock, but i'll look into to see if there is a way to bypass the lock without waiting for it.

**Comment by mehranexpert** [comment]
good , whats about instagram  ? is it block account ? any account i founded it got locked and need checkpoint do you know how can fix locked accounts ?
