### ISSUE TITLE
add total password Count & time

### ISSUE THREAD

**Issue by Mehran** [Ethical-H4CK3R/Pulse#9]
can you add total password count and start time count under here 

```
print '  {}[-] Web-Site: {}{}'.format(W,G,website)
  print '  {}[-] Proxy Ip: {}{}'.format(W,G,proxyIp)
  print '  {}[-] Wordlist: {}{}'.format(W,G,wordlist)
  print '  {}[-] Username: {}{}'.format(W,G,username)
  print '  {}[-] Password: {}{}'.format(W,G,password)
  print '  {}[-] Attempts: {}{}'.format(W,G,attempts)

```

**Comment by Ethical-H4CK3R** [comment]
can you explain what you mean by that

**Comment by Mehran** [comment]
i mean it show how many count password is in list while cracking , under Attemps and time elapsed while cracking .

**Comment by Ethical-H4CK3R** [comment]
that makes the computer run slow, because in order to do that, the whole password file has to be saved into memory.
